[theme]
primaryColor = "#118DFF"
backgroundColor = "#F4F6F9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#182230"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
